### PR TITLE
Connections

### PR DESCRIPTION
**Pull request by nemchik**
I am not sure what the best practice is for adding the language translations.

In the `Database` class I have renamed `$connections` to `$dsn_array` to avoid collision with the new configurations. This should not have any effect functionally.

So far, I have only tested MySQL. The others are written out based on information about the drivers from https://www.php.net/manual/en/pdo.drivers.php

I had previously developed this as a separate plugin, used in conjunction with the Database plugin v1.0.2. ~~I have not yet tested directly modifying the database plugin with these changes. I will test this and report the status likely tomorrow and update this comment.~~ I have now fully tested these changes (with MySQL) by replacing my database plugin folder with the contents of my branch. I wanted to get this PR open for some initial review/feedback.

The changes to `classes/PDO.php` are cosmetic and were done using https://loilo.github.io/prettier-php-playground/

An example of using the new functionality in a theme's twig template (after adding a database configuration) would be:
In your theme php
```php
    /**
     * Provide the db variable to twig
     */
    public function onTwigSiteVariables(): void
    {
        $this->grav["twig"]->twig_vars["db"] = Grav::instance()['database'];
    }
```
In your twig template
```twig
{% set dbresults = db.mysql("testcon").selectall("SELECT * FROM testtable WHERE testcol1 != :id", {id: '3'}) %}
{% if dbresults is iterable %}
<table>
    <thead>
        <tr>
        {% for key in dbresults|first|keys %}
            <th>{{ key }}</th>
        {% endfor %}
        <tr>
    </thead>
    <tbody>
        {% for row in dbresults %}
        <tr>
            {% for col in row %}
                <td>{{ col }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
```

And I imagine https://github.com/gamahachaa/grav-plugin-form-database could also leverage the new functionality as well (I wrote my own way of doing this with the changes in this PR before realizing the form database plugin existed - I might PR the form database repo as well if this merges)

### CODE REVIEW

**Review by gamahachaa — APPROVED** [review]
Thanks !

**Comment by nemchik** [comment]
Converted to draft after looking at @gamahachaa 's form database plugin, I've had some inspiration to remove some repetition. (I will try to get to it tomorrow). Still open to any feedback in the meantime.

**Comment by nemchik** [comment]
Ok, new changes are in. Mostly DRY (condensed the repeated driver classes into the `Database` class).

**Comment by rhukster** [comment]
Reading over the code, it seems pretty good to me.  I need to actually make a little time to test out the functionality however.  I will hopefully get to this next week and approve it if all goes well.  Cheers!

**Comment by nemchik** [comment]
@rhukster checking back on this to see if you have time to review. I've been using it personally and it's been working fine for my use.

**Comment by rhukster** [comment]
I've tested with 'views' plugin (the only one i had installed) and it seems to work fine with that (backwards compatibility wise).  The only thing I would like to see is an example of how to use another db connection in the README.md.

I see you updated the README.md but only with minor variable name changes.  Cheers!

**Comment by nemchik** [comment]
> I would like to see is an example of how to use another db connection in the README.md.

Done in https://github.com/getgrav/grav-plugin-database/pull/6/commits/bbd49dc4e81b9d2f6c0ec0c9a652bc893c5abddc

**Comment by rhukster** [comment]
Looks great thanks!  if you find any more tweaks or need some changes, feel free to create a new PR.  cheers.

**Pull request merged**
